"""fix_user_model

Revision ID: 19e7d628cf02
Revises: ba7a1dd43d69
Create Date: 2026-05-06 23:09:41.136405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e7d628cf02'
down_revision: Union[str, Sequence[str], None] = 'ba7a1dd43d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('FREE', 'PRO', 'BUSINESS', name='subscriptiontier', native_enum=False, length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'subscription',
               existing_type=sa.Enum('FREE', 'PRO', 'BUSINESS', name='subscriptiontier', native_enum=False, length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    # ### end Alembic commands ###
